name: Maven CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  maven-build:
    name: Build, Test and Package
    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Java 8
        run: |
          java -version

      - name: Verify Maven
        run: |
          ./mvnw -version

      - name: Compile Application
        run: |
          ./mvnw -B compile

      - name: Run Tests
        run: |
          ./mvnw -B test

      - name: Package WAR
        run: |
          ./mvnw -B package -DskipTests

      - name: Verify WAR
        run: |
          ls -lh target/*.war
